/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author user
 */
public class ParticipantHome_jframe extends javax.swing.JFrame {

    /**
     * Creates new form ParticipantHome
     */
    static int ID;
    public int getID() {
        return ID;} 
    public void setID(int ID) {
        this.ID = ID;}
    
    public ParticipantHome_jframe() {//if run file
        System.out.println("Please run Project");
    }
    public ParticipantHome_jframe(int Id) {//if run project
        initComponents();
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);//make jframe center
        
        setID(Id);
        Personnel sys = new Personnel();
        People user=new People(ID);
                
        //String[] user_data=sys.search_onePeep_byID(ID);
        String firstname= (user.getPeepFullname().split(" "))[0];
        hi_lbl.setText("Hi, "+firstname);//assign the name to the label
        if(!(user.getPeepAppid().equals("none"))){
            btnAppoint.setEnabled(false);
            btnCancel.setEnabled(true);
        }
        try{
            Appointment app = new Appointment();
            String [] peepdata = app.search_byPeepID(ID).get(0).split(",");
            lblappID.setText(peepdata[0]);
            lblDate.setText(peepdata[1]);
            Vaccine vacc= new Vaccine(Integer.parseInt(peepdata[2]));
            lblvacName.setText(vacc.getVacName());
            lblvacLoc.setText(vacc.getVacLoc());
        }catch(Exception e){
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAppoint = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        btnVac = new javax.swing.JButton();
        logout_btn = new javax.swing.JButton();
        hi_lbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblappID = new javax.swing.JLabel();
        lblvacName = new javax.swing.JLabel();
        lblvacLoc = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Participant");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Home");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 485, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAppoint.setText("Submit Appointment");
        btnAppoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppointActionPerformed(evt);
            }
        });
        jPanel2.add(btnAppoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 158, 54));

        btnProfile.setText("Profile");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });
        jPanel2.add(btnProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 156, 54));

        btnVac.setText("Vaccine Status");
        btnVac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVacActionPerformed(evt);
            }
        });
        jPanel2.add(btnVac, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 158, 54));

        logout_btn.setText("Log Out");
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });
        jPanel2.add(logout_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 158, 54));

        hi_lbl.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        hi_lbl.setText("Hi, User");
        jPanel2.add(hi_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblappID.setText("none");
        jPanel3.add(lblappID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 100, 20));

        lblvacName.setText("none");
        jPanel3.add(lblvacName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 130, 20));

        lblvacLoc.setText("none");
        jPanel3.add(lblvacLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 120, 20));

        jLabel9.setText("Vaccine Location");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel10.setText("Appointment ID");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel11.setText("Vaccine Name");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel3.setText("Appointment Date");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        lblDate.setText("none");
        jPanel3.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 180, 20));

        btnCancel.setText("Cancel");
        btnCancel.setEnabled(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 180, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Appointment Info");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 130, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 380, 220));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 810, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ParticipantProfile_jframe(ID).setVisible(true);
    }//GEN-LAST:event_btnProfileActionPerformed

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_logout_btnActionPerformed

    private void btnAppointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppointActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ParticipantAppointment_jframe(ID, "participant").setVisible(true);
    }//GEN-LAST:event_btnAppointActionPerformed

    private void btnVacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVacActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ParticipantSupply_jframe(ID).setVisible(true);
    }//GEN-LAST:event_btnVacActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        int appid=Integer.parseInt(lblappID.getText());
        String appdate= lblDate.getText();
        int peepID=ID;
        Appointment app = new Appointment();
        String [] appdetail = app.search_byPeepID(ID).get(0).split(",");
        int vacID=Integer.parseInt(appdetail[2]);
        String new_data=(appid+","+appdate+","+vacID+","+peepID);

        //remove.
        Appointment vacSys = new Appointment();
        vacSys.remove_app(new_data);
        //pop up box successful or not
        //JOptionPane.showMessageDialog(null,"Update Succesfull");
        lblappID.setText("none");
        lblDate.setText("none");
        lblvacName.setText("none");
        lblvacLoc.setText("none");
        btnAppoint.setEnabled(true);
        btnCancel.setEnabled(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParticipantHome_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParticipantHome_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParticipantHome_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParticipantHome_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParticipantHome_jframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppoint;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnVac;
    private javax.swing.JLabel hi_lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblappID;
    private javax.swing.JLabel lblvacLoc;
    private javax.swing.JLabel lblvacName;
    private javax.swing.JButton logout_btn;
    // End of variables declaration//GEN-END:variables
}
