/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author user
 */
public class ParticipantAppointment_jframe extends javax.swing.JFrame {
    static int id;
    static String user;
    Appointment app = new Appointment();

    /**
     * Creates new form SubmitAppointment
     */
    public ParticipantAppointment_jframe() {//if just run file
        System.out.println("Please run Project");
    }
    
    public ParticipantAppointment_jframe(int id,String user) {//if run project
        this.id=id;//get id from the previous jframe
        this.user=user;//get user from the previous jframe
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);//to center the jframe
        if(user.equals("admin")){//set label depending on the user
            lblUser.setText("Personnel");
        }else{
            lblUser.setText("Participant");
        }
        
        ArrayList<Integer> day = new ArrayList<>();//to set the day and year combo box
        for(int i = 1; i <= 31; i++) {
            day.add(i);
        }
        Integer[]dayArray=day.toArray(new Integer[0]);
        DefaultComboBoxModel days = new DefaultComboBoxModel(dayArray);
        cmbDate.setModel(days);

        ArrayList<Integer> year = new ArrayList<>();
        LocalDate current_date = LocalDate.now();
        int current_year=current_date.getYear();
        for(int i = current_year; i <= 2025; i++) {
            year.add(i);
        }
        Integer[]yearArray=year.toArray(new Integer[0]);
        DefaultComboBoxModel years = new DefaultComboBoxModel(yearArray);
        cmbYear.setModel(years);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        back_btn1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        cmbVaccTemp = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmbLocationTemp = new javax.swing.JComboBox<>();
        cmbDate = new javax.swing.JComboBox<>();
        cmbMonth = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmbYear = new javax.swing.JComboBox<>();
        btnBookApp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Book Appointment");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        lblUser.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Submit Appointment");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblUser)
                .addContainerGap(681, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(425, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(37, 37, 37)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(23, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(2, 2, 2)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 100));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back_btn1.setText("<--- Go Back");
        back_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(back_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 130, 50));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbVaccTemp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CoronaVac", "Johnson & Johnson", "Moderna", "Sinopharm", "Pfizer" }));
        jPanel3.add(cmbVaccTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 140, -1));

        jLabel11.setText("Vaccine Name");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel9.setText("Vaccine Location");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        cmbLocationTemp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NorthWood", "EastWood", "SouthWood", "WestWood" }));
        jPanel3.add(cmbLocationTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 140, -1));

        jPanel3.add(cmbDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 50, -1));

        cmbMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        cmbMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMonthActionPerformed(evt);
            }
        });
        jPanel3.add(cmbMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jLabel3.setText("Appointment Date");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jPanel3.add(cmbYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 310, 240));

        btnBookApp.setText("Book Appointment");
        btnBookApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookAppActionPerformed(evt);
            }
        });
        jPanel2.add(btnBookApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 150, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 700, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMonthActionPerformed
        // TODO add your handling code here:
        int Month=cmbMonth.getSelectedIndex();//to change the date depending on the month
        int[] one = { 0, 2, 4, 6, 7, 9, 11};
        int[] thirtee = { 3, 5, 8, 10};
        boolean foundOne = false;
        boolean foundThre=false;
        for (int n : one) {
            if (n == Month) {
                foundOne = true;
                break;
            }
        }
        for (int n : thirtee) {
            if (n == Month) {
                foundThre = true;
                break;
            }
        }
        cmbDate.removeAllItems();
        if(foundOne == true){
            String [] date = new String[31];
            for(int i = 0; i < 31; i++) {
                date[i] = String.valueOf(i + 1);
            }
            DefaultComboBoxModel days = new DefaultComboBoxModel(date);
            cmbDate.setModel(days);
        }
        else if (foundThre == true){
            String [] date = new String[30];
            for(int i = 0; i < 30; i++) {
                date[i] = String.valueOf(i + 1);
            }
            DefaultComboBoxModel days = new DefaultComboBoxModel(date);
            cmbDate.setModel(days);
        }
        else{
            String [] date = new String[28];
            for(int i = 0; i < 28; i++) {
                date[i] = String.valueOf(i + 1);
            }
            DefaultComboBoxModel days = new DefaultComboBoxModel(date);
            cmbDate.setModel(days);
        }
    }//GEN-LAST:event_cmbMonthActionPerformed

    private void back_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btn1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        if(user.equals("admin")){//if the user is admin return to admin
            new PersonnelViewParticipant_jframe().setVisible(true);
        }else{//if the user is participant return to participant
            new ParticipantHome_jframe(id).setVisible(true);
        }
    }//GEN-LAST:event_back_btn1ActionPerformed

    private void btnBookAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookAppActionPerformed
        // TODO add your handling code here:
        String D=String.valueOf(cmbDate.getSelectedItem());
        int Month=cmbMonth.getSelectedIndex();
        String M=String.valueOf(Month+1);
        String Y=String.valueOf(cmbYear.getSelectedItem());
        String app_date= D+"/"+M+"/"+Y; //get data from combo box to form a date and combine it
        String vac_name=(String) cmbVaccTemp.getSelectedItem();
        String vac_location=(String) cmbLocationTemp.getSelectedItem();
        if(app.add_Application(app_date, vac_name, vac_location, id)==true){//if code is successfull returns user
            if(user.equals("admin")){//if the user is admin return to admin
                new PersonnelViewParticipant_jframe().setVisible(true);
                this.dispose();
            }else{//if the user is participant return to participant
                new ParticipantHome_jframe(id).setVisible(true);
                this.dispose();
            }
        }else{//if booking fails clear the data
            cmbVaccTemp.setSelectedIndex(0);
            cmbLocationTemp.setSelectedIndex(0);
            cmbDate.setSelectedIndex(0);
            cmbYear.setSelectedIndex(0);
            cmbMonth.setSelectedIndex(0);
        }
    }//GEN-LAST:event_btnBookAppActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParticipantAppointment_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParticipantAppointment_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParticipantAppointment_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParticipantAppointment_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParticipantAppointment_jframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn1;
    private javax.swing.JButton btnBookApp;
    private javax.swing.JComboBox<String> cmbDate;
    private javax.swing.JComboBox<String> cmbLocationTemp;
    private javax.swing.JComboBox<String> cmbMonth;
    private javax.swing.JComboBox<String> cmbVaccTemp;
    private javax.swing.JComboBox<String> cmbYear;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables
}
