/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author user
 */
public class PersonnelSupply_jframe extends javax.swing.JFrame {
    Vaccine vacc = new Vaccine();

    /**
     * Creates new form PersonnelSupply_jframe
     */
    public PersonnelSupply_jframe() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);//make jframe center
        ArrayList<String> vacArray = vacc.view_all_details();
        input_table(vacArray);
        btnModify.setEnabled(false);
        btnRmv.setEnabled(false);
        btnClear.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSupply = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmbVaccTemp = new javax.swing.JComboBox<>();
        cmbLocationTemp = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        vacc_table = new javax.swing.JTable();
        txtID = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnRmv = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        cmbVacc = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbLocation = new javax.swing.JComboBox<>();
        back_btn1 = new javax.swing.JButton();
        all_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Supply");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(810, 550));
        setResizable(false);
        setSize(new java.awt.Dimension(810, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblID.setText("-");
        jPanel3.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 130, 20));

        jLabel9.setText("Vaccine Location");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        jPanel3.add(txtSupply, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 140, -1));

        jLabel10.setText("ID");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel11.setText("Vaccine Name");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        cmbVaccTemp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CoronaVac", "Johnson & Johnson", "Moderna", "Sinopharm", "Pfizer" }));
        jPanel3.add(cmbVaccTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 140, -1));

        cmbLocationTemp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NorthWood", "EastWood", "SouthWood", "WestWood" }));
        jPanel3.add(cmbLocationTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 140, -1));

        jLabel6.setText("Supply");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 50, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 300, 220));

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Personnel");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Supply");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 90));

        vacc_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Vaccine Name", "Vaccine Location", "Supply"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        vacc_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vacc_tableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(vacc_table);
        if (vacc_table.getColumnModel().getColumnCount() > 0) {
            vacc_table.getColumnModel().getColumn(0).setResizable(false);
            vacc_table.getColumnModel().getColumn(1).setResizable(false);
            vacc_table.getColumnModel().getColumn(2).setResizable(false);
            vacc_table.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 460, 300));

        txtID.setText("Search by ID");
        txtID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIDFocusLost(evt);
            }
        });
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 190, -1));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        btnModify.setText("Modify");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        getContentPane().add(btnModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 140, 40));

        btnAdd.setText("Add Supply");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 150, 40));

        btnRmv.setText("Remove");
        btnRmv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRmvActionPerformed(evt);
            }
        });
        getContentPane().add(btnRmv, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 150, 40));

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 140, 40));

        cmbVacc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "CoronaVac", "Johnson & Johnson", "Moderna", "Sinopharm", "Pfizer" }));
        cmbVacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVaccActionPerformed(evt);
            }
        });
        getContentPane().add(cmbVacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 140, -1));

        jLabel3.setText("Centre Location");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 120, -1));

        jLabel4.setText("Vaccine Type");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 90, -1));

        jLabel8.setText("Search");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        cmbLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "NorthWood", "EastWood", "SouthWood", "WestWood" }));
        cmbLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLocationActionPerformed(evt);
            }
        });
        getContentPane().add(cmbLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 120, -1));

        back_btn1.setText("<--- Go Back");
        back_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(back_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, 130, 40));

        all_btn.setText("View All Supply");
        all_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                all_btnActionPerformed(evt);
            }
        });
        getContentPane().add(all_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void input_table(ArrayList<String> vaccArray){ //call this function whenever need to update the table
                                //use the arraylist to input table
        DefaultTableModel model = (DefaultTableModel)vacc_table.getModel();//The table variable
        model.setRowCount(0);//clear table
        try{
            for(String vac:vaccArray){
                //insert a data into table
                String[] data_row = vac.split(",");
                if(data_row[3].equals("0")){}
                else{
                    String[] selected_data={data_row[0],data_row[1],data_row[2],data_row[3]};   //must select the data in each array into the table
                    model.addRow(selected_data);
                }
            }
        }
        catch(Exception e){
            System.out.println("Table error");
        }
    }
    
    private void vacc_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vacc_tableMouseClicked
        // TODO add your handling code here:
        int i = vacc_table.getSelectedRow();
        TableModel model=vacc_table.getModel();
        int id = Integer.parseInt(model.getValueAt(i, 0).toString());
        ArrayList<String> selected_data = vacc.search_byVacID(id);
        Vaccine vac = new Vaccine(selected_data.get(0));
        lblID.setText(String.valueOf(vac.getVacID()));
        cmbVaccTemp.setSelectedItem(vac.getVacName());
        cmbLocationTemp.setSelectedItem(vac.getVacLoc());
        cmbVaccTemp.setEnabled(false);
        cmbLocationTemp.setEnabled(false);
        txtSupply.setText(vac.getVacSupp());//assign the data to the label panel
        btnAdd.setEnabled(false);//make add supply unclickable
        btnModify.setEnabled(true);
        btnRmv.setEnabled(true);
        btnClear.setEnabled(true);//make the other function clickable
    }//GEN-LAST:event_vacc_tableMouseClicked

    private void txtIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIDFocusGained
        // TODO add your handling code here:
        if("Search by ID".equals(txtID.getText())){
            txtID.setText("");
        }
    }//GEN-LAST:event_txtIDFocusGained

    private void txtIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIDFocusLost
        // TODO add your handling code here:
        if(txtID.getText().length()==0){
            txtID.setText("Search by ID");
        }
    }//GEN-LAST:event_txtIDFocusLost
    private void clearArea(){//clear all the label and combobox from the panel
        btnAdd.setEnabled(true);
        btnModify.setEnabled(false);
        btnRmv.setEnabled(false);
        btnClear.setEnabled(false);
        cmbVaccTemp.setSelectedIndex(0);
        cmbLocationTemp.setSelectedIndex(0);
        cmbVacc.setSelectedIndex(0);
        cmbLocation.setSelectedIndex(0);
        cmbVaccTemp.setEnabled(true);
        cmbLocationTemp.setEnabled(true);
        txtSupply.setText("");
        lblID.setText("-");
        vacc_table.clearSelection();
    }
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearArea();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String name=(String) cmbVaccTemp.getSelectedItem();
        String location=(String) cmbLocationTemp.getSelectedItem(); //get the vaccine name and location
        try{
            Integer.parseInt(txtSupply.getText());//validate if supply is interger
            int supply=Integer.parseInt(txtSupply.getText());
            ArrayList <String> vacArrayList=vacc.search_by_details(name, location);//search by name and location
            Vaccine VC=new Vaccine(vacArrayList.get(0));
            int newSupp= Integer.parseInt(VC.getVacSupp())+supply;//old supply+new supply
            VC.setVacSupp(String.valueOf(newSupp));
            vacc.modify_vacc(VC.return_string());
            
            ArrayList<String> vacArray = vacc.view_all_details();//view all detail
            input_table(vacArray);
            clearArea();
        }
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,"Input Incorrect\nPlease Check Again");
        }
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        // TODO add your handling code here:
        String name=(String) cmbVaccTemp.getSelectedItem();
        String location=(String) cmbLocationTemp.getSelectedItem();//get the vaccine name and location
        try{
            Integer.parseInt(txtSupply.getText());//validate if supply is interger
            int supply=Integer.parseInt(txtSupply.getText());
            ArrayList <String> vacArrayList=vacc.search_by_details(name, location);//search by name and location
            Vaccine VC=new Vaccine(vacArrayList.get(0));
            int newSupp= supply;//the inputted supply becomes the supply
            VC.setVacSupp(String.valueOf(newSupp));
            vacc.modify_vacc(VC.return_string());
            
            ArrayList<String> vacArray = vacc.view_all_details();//view all detail
            input_table(vacArray);
            clearArea();
        }
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,"Input Incorrect\nPlease Check Again");
        }
        
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnRmvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRmvActionPerformed
        // TODO add your handling code here:
        String name=(String) cmbVaccTemp.getSelectedItem();
        String location=(String) cmbLocationTemp.getSelectedItem();//get the vaccine name and location
        try{
            Integer.parseInt(txtSupply.getText());//validate if supply is interger
            ArrayList <String> vacArrayList=vacc.search_by_details(name, location);//search by name and location
            Vaccine VC=new Vaccine(vacArrayList.get(0));
            int newSupp= 0;//set the supply to 0
            VC.setVacSupp(String.valueOf(newSupp));
            vacc.modify_vacc(VC.return_string());

            ArrayList<String> vacArray = vacc.view_all_details();//view all detail
            input_table(vacArray);
            clearArea();
        }
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,"Input Incorrect\nPlease Check Again");
        }
    }//GEN-LAST:event_btnRmvActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try{
            ArrayList<String> vac_data_arrlist=new ArrayList<>();
            int id=Integer.parseInt(txtID.getText());
            String vac_name=(String) cmbVacc.getSelectedItem();
            String vac_loc=(String) cmbLocation.getSelectedItem();

            if(vac_name=="All" && vac_loc=="All"){
                vac_data_arrlist = vacc.search_byVacID(id);
                if (vac_data_arrlist==null){
                    JOptionPane.showMessageDialog(null,"ID Not Found");
                    txtID.setText("Search by ID");
                } else{ //display to the table
                    input_table(vac_data_arrlist);
                }
            }
            else if(vac_loc=="All"){//search according to vac name and id
                vac_data_arrlist = vacc.search_by_id_name(id,vac_name); //

                if (vac_data_arrlist==null){
                    JOptionPane.showMessageDialog(null,"ID Not Found");
                    txtID.setText("Search by ID");
                } else{ //display to the table
                    input_table(vac_data_arrlist);
                }
            }
            //all selected
            else if(vac_name=="All"){//search according to vac location and id
                vac_data_arrlist = vacc.search_by_id_loc(id,vac_loc); //

                if (vac_data_arrlist==null){
                    JOptionPane.showMessageDialog(null,"ID Not Found");
                    txtID.setText("Search by ID");
                } else{ //display to the table
                    input_table(vac_data_arrlist);
                }
            }
            else{//search according to vac name, location, and id
                vac_data_arrlist = vacc.search(id,vac_name,vac_loc);
                if (vac_data_arrlist==null){
                    JOptionPane.showMessageDialog(null,"ID Not Found");
                    txtID.setText("Search by ID");
                } else{ //display to the table
                    input_table(vac_data_arrlist);
                }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Please input correct ID");
            txtID.setText("Search by ID");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void check_cmbbox(){
        ArrayList<String> vac_data_arrlist=new ArrayList<>();
        String vac_name=(String) cmbVacc.getSelectedItem();
        String vac_loc=(String) cmbLocation.getSelectedItem();
        //all all
        if(vac_name=="All" && vac_loc=="All"){//view all detail
            ArrayList<String> vacArray = vacc.view_all_details();
            input_table(vacArray);
        }
        //selected all //check name
        else if(vac_loc=="All"){//search vac name
            vac_data_arrlist = vacc.search_byVacName(vac_name);
            input_table(vac_data_arrlist);
        }
        //all selected
        else if(vac_name=="All"){//search vac loc
            vac_data_arrlist = vacc.search_byVacLoc(vac_loc);
            input_table(vac_data_arrlist);
        }
        //selected selected
        else{//search vac name and location
            vac_data_arrlist = vacc.search_by_details(vac_name, vac_loc);
            input_table(vac_data_arrlist);
        }
    }
    
    private void cmbVaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVaccActionPerformed
        // TODO add your handling code here:
        check_cmbbox();
    }//GEN-LAST:event_cmbVaccActionPerformed

    private void cmbLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLocationActionPerformed
        // TODO add your handling code here:
        check_cmbbox();
    }//GEN-LAST:event_cmbLocationActionPerformed

    private void back_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btn1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        //Goes back to participantHome_jframe
        new PersonnelHome_jframe().setVisible(true);
    }//GEN-LAST:event_back_btn1ActionPerformed

    private void all_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_all_btnActionPerformed
        // TODO add your handling code here:
        ArrayList<String> vacArray = vacc.view_all_details();
        input_table(vacArray);
        btnModify.setEnabled(false);
        btnRmv.setEnabled(false);
        btnClear.setEnabled(false);
        btnAdd.setEnabled(true);
        lblID.setText("-");
        cmbVacc.setSelectedIndex(0);
        cmbLocation.setSelectedIndex(0);
        cmbVaccTemp.setSelectedIndex(0);
        cmbLocationTemp.setSelectedIndex(0);
        txtSupply.setText("");//view all detail and set all label panel to empty        
    }//GEN-LAST:event_all_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonnelSupply_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonnelSupply_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonnelSupply_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonnelSupply_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonnelSupply_jframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton all_btn;
    private javax.swing.JButton back_btn1;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnRmv;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbLocation;
    private javax.swing.JComboBox<String> cmbLocationTemp;
    private javax.swing.JComboBox<String> cmbVacc;
    private javax.swing.JComboBox<String> cmbVaccTemp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblID;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtSupply;
    private javax.swing.JTable vacc_table;
    // End of variables declaration//GEN-END:variables
}
