/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author user
 */
public class PersonnelAppointment_jframe extends javax.swing.JFrame {
    Appointment app = new Appointment();

    /**
     * Creates new form PersonnelAppointment_jframe
     */
    public PersonnelAppointment_jframe() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
        btnModify.setEnabled(false);
        btnDelete.setEnabled(false);
        ArrayList<Integer> day = new ArrayList<>();
        for(int i = 1; i <= 31; i++) {
            day.add(i);
        }
        Integer[]dayArray=day.toArray(new Integer[0]);
        DefaultComboBoxModel days = new DefaultComboBoxModel(dayArray);
        cmbDate.setModel(days);

        ArrayList<Integer> year = new ArrayList<>();
        //LocalDate current_date = LocalDate.now();
        //int current_year=current_date.getYear();
        for(int i = 2021; i <= 2025; i++) {
            year.add(i);
        }
        Integer[]yearArray=year.toArray(new Integer[0]);
        DefaultComboBoxModel years = new DefaultComboBoxModel(yearArray);
        cmbYear.setModel(years);
        ArrayList<String> appArray = app.view_all_details();
        input_table(appArray);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table_app = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        cmbDate = new javax.swing.JComboBox<>();
        cmbMonth = new javax.swing.JComboBox<>();
        cmbYear = new javax.swing.JComboBox<>();
        lblappID = new javax.swing.JLabel();
        lblvacName = new javax.swing.JLabel();
        lblvacLoc = new javax.swing.JLabel();
        lblpeepName = new javax.swing.JLabel();
        lblpeepStatus = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnModify = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        all_part_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Appointment");
        setMinimumSize(new java.awt.Dimension(957, 555));
        setPreferredSize(new java.awt.Dimension(957, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Table_app.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "AppointmentID", "AppointmentDate", "SupplyID", "PeopleID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_app.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_appMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_app);
        if (Table_app.getColumnModel().getColumnCount() > 0) {
            Table_app.getColumnModel().getColumn(0).setResizable(false);
            Table_app.getColumnModel().getColumn(1).setResizable(false);
            Table_app.getColumnModel().getColumn(2).setResizable(false);
            Table_app.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 440, 320));

        jPanel1.setBackground(new java.awt.Color(255, 0, 51));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Personnel");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Appointment");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 544, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(82, 82, 82))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(34, 34, 34))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 110));

        jLabel8.setText("Search");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txtID.setText("Search by People's ID");
        txtID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIDFocusLost(evt);
            }
        });
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 160, -1));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        back_btn.setText("<--- Go Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        getContentPane().add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, 200, 40));

        clear_btn.setText("Clear Data");
        clear_btn.setEnabled(false);
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });
        getContentPane().add(clear_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 470, 180, 40));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.add(cmbDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 50, -1));

        cmbMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        cmbMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMonthActionPerformed(evt);
            }
        });
        jPanel3.add(cmbMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        jPanel3.add(cmbYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));
        jPanel3.add(lblappID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 100, 20));
        jPanel3.add(lblvacName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 130, 20));
        jPanel3.add(lblvacLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 120, 20));
        jPanel3.add(lblpeepName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 100, 20));
        jPanel3.add(lblpeepStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 160, 20));

        jLabel9.setText("Vaccine Location");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel10.setText("Appointment ID");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel11.setText("Vaccine Name");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel3.setText("Appointment Date");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel4.setText("People Name");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 100, -1));

        jLabel5.setText("People Status");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 80, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 400, 250));

        btnModify.setText("Modify");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        getContentPane().add(btnModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, 200, 40));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 410, 180, 40));

        all_part_btn.setText("All Participant");
        all_part_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                all_part_btnActionPerformed(evt);
            }
        });
        getContentPane().add(all_part_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 110, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void input_table(ArrayList<String> appArray){ //call this function whenever need to update the table
                                //use the arraylist to input table
        DefaultTableModel model = (DefaultTableModel)Table_app.getModel();//The table variable
        model.setRowCount(0);
        for(String line:appArray){
            //insert a data into table
            String[] data_row = line.split(",");
            String[] selected_data={data_row[0],data_row[1],data_row[2],data_row[3]};   //must select the data in each array into the table
            model.addRow(selected_data);
        }
    }
    private void txtIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIDFocusGained
        // TODO add your handling code here:
        if("Search by People's ID".equals(txtID.getText())){
            txtID.setText("");
        }
    }//GEN-LAST:event_txtIDFocusGained

    private void txtIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIDFocusLost
        // TODO add your handling code here:
        if(txtID.getText().length()==0){
            txtID.setText("Search by People's ID");
        }
    }//GEN-LAST:event_txtIDFocusLost

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        try{
            ArrayList<String> vac_data=new ArrayList<>();
            int id=Integer.parseInt(txtID.getText());//get ID
            vac_data = app.search_byPeepID(id);
                if (vac_data==null){
                    JOptionPane.showMessageDialog(null,"ID Not Found");
                    txtID.setText("Search by ID");
                } else{ //display to the table
                    input_table(vac_data);
                }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Please input correct ID");
            txtID.setText("Search by ID");
        }
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new PersonnelHome_jframe().setVisible(true);
    }//GEN-LAST:event_back_btnActionPerformed

    private void cmbMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMonthActionPerformed
        // TODO add your handling code here:
        int Month=cmbMonth.getSelectedIndex();//determine the number of day for the according month
        int[] one = { 0, 2, 4, 6, 7, 9, 11};
        int[] thirtee = { 3, 5, 8, 10};
        boolean foundOne = false;
        boolean foundThre=false;
        for (int n : one) {
            if (n == Month) {
                foundOne = true;
                break;
            }
        }
        for (int n : thirtee) {
            if (n == Month) {
                foundThre = true;
                break;
            }
        }
        cmbDate.removeAllItems();
        if(foundOne == true){
            String [] date = new String[31];
            for(int i = 0; i < 31; i++) {
                date[i] = String.valueOf(i + 1);
            }
            DefaultComboBoxModel days = new DefaultComboBoxModel(date);
            cmbDate.setModel(days);
        }
        else if (foundThre == true){
            String [] date = new String[30];
            for(int i = 0; i < 30; i++) {
                date[i] = String.valueOf(i + 1);
            }
            DefaultComboBoxModel days = new DefaultComboBoxModel(date);
            cmbDate.setModel(days);
        }
        else{
            String [] date = new String[28];
            for(int i = 0; i < 28; i++) {
                date[i] = String.valueOf(i + 1);
            }
            DefaultComboBoxModel days = new DefaultComboBoxModel(date);
            cmbDate.setModel(days);
        }
    }//GEN-LAST:event_cmbMonthActionPerformed

    private void Table_appMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_appMouseClicked
        // TODO add your handling code here:
        int i = Table_app.getSelectedRow();
        TableModel model=Table_app.getModel();
        int peepid = Integer.parseInt(model.getValueAt(i, 3).toString());
        ArrayList<String> selected_data = app.search_byPeepID(peepid);
        Appointment appoint = new Appointment(selected_data.get(0));
        Vaccine vacc= new Vaccine(appoint.getVaccID());
        People peep = new People(appoint.getPeepID());
        lblappID.setText(String.valueOf(appoint.getAppID()));
        String date=appoint.getAppDate();
        String [] date_detail = date.split("/");
        cmbMonth.setSelectedIndex(Integer.parseInt(date_detail[1])-1);
        cmbDate.setSelectedIndex(Integer.parseInt(date_detail[0])-1);
        cmbYear.setSelectedItem(Integer.parseInt(date_detail[2]));//put the data into combo box
        lblvacName.setText(vacc.getVacName());
        lblvacLoc.setText(vacc.getVacLoc());
        lblpeepName.setText(peep.getPeepFullname());
        lblpeepStatus.setText(peep.getPeepStatus());//assign the data to the label panel
        btnDelete.setEnabled(true);//allows the user to delete and modify data
        btnModify.setEnabled(true);
        clear_btn.setEnabled(true);//allows the user to clear panel
    }//GEN-LAST:event_Table_appMouseClicked

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        // TODO add your handling code here:
        int appid=Integer.parseInt(lblappID.getText());
        String D=String.valueOf(cmbDate.getSelectedItem());
        int Month=cmbMonth.getSelectedIndex();
        String M=String.valueOf(Month+1);
        String Y=String.valueOf(cmbYear.getSelectedItem());
        String appdate= D+"/"+M+"/"+Y;//combine data to string
        int i = Table_app.getSelectedRow();
        TableModel model=Table_app.getModel();
        int peepid = Integer.parseInt(model.getValueAt(i, 3).toString());//get peepid
        ArrayList<String> selected_data = app.search_byPeepID(peepid);
        Appointment appoint = new Appointment(selected_data.get(0));
        int vacID=appoint.getVaccID();
        int peepID=appoint.getPeepID();
        String new_data=(appid+","+appdate+","+vacID+","+peepID);
        String current_data=(new Appointment().search_byPeepID(peepID)).get(0);
        if(new_data.equals(current_data)){//the old data is similar to the new data
            JOptionPane.showMessageDialog(null,"Inserted data the same as before, update failed");
        }
        else{
            //modify.
            Appointment vacSys = new Appointment();
            vacSys.modify_app(new_data);
        }
        clear_selected();
        ArrayList<String> appArray = app.view_all_details();
        input_table(appArray);//show all
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int appid=Integer.parseInt(lblappID.getText());
        String D=String.valueOf(cmbDate.getSelectedItem());
        int Month=cmbMonth.getSelectedIndex();
        String M=String.valueOf(Month+1);
        String Y=String.valueOf(cmbYear.getSelectedItem());
        String appdate= D+"/"+M+"/"+Y;//combine data to string
        int i = Table_app.getSelectedRow();
        TableModel model=Table_app.getModel();
        int peepid = Integer.parseInt(model.getValueAt(i, 3).toString());//get peepid
        ArrayList<String> selected_data = app.search_byPeepID(peepid);
        Appointment appoint = new Appointment(selected_data.get(0));
        int vacID=appoint.getVaccID();
        int peepID=appoint.getPeepID();//get peepID and vacID from the appointment class
        String new_data=(appid+","+appdate+","+vacID+","+peepID);
        
        //remove.
        Appointment vacSys = new Appointment();
        vacSys.remove_app(new_data);
        
        clear_selected();
        ArrayList<String> appArray = app.view_all_details();
        input_table(appArray);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        // TODO add your handling code here:
        clear_selected();
    }//GEN-LAST:event_clear_btnActionPerformed

    private void all_part_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_all_part_btnActionPerformed
        // TODO add your handling code here:
        clear_selected();
        ArrayList<String> appArray = app.view_all_details();
        input_table(appArray);
    }//GEN-LAST:event_all_part_btnActionPerformed
    private void clear_selected(){
            btnModify.setEnabled(false);
            clear_btn.setEnabled(false);
            btnDelete.setEnabled(false);
            lblappID.setText("-");
            lblvacName.setText("");
            lblvacLoc.setText("");
            lblpeepName.setText("");
            lblpeepStatus.setText("");
            cmbDate.setSelectedIndex(0);
            cmbYear.setSelectedIndex(0);
            cmbMonth.setSelectedIndex(0);
            //set all text box to empty
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonnelAppointment_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonnelAppointment_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonnelAppointment_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonnelAppointment_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonnelAppointment_jframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_app;
    private javax.swing.JButton all_part_btn;
    private javax.swing.JButton back_btn;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton clear_btn;
    private javax.swing.JComboBox<String> cmbDate;
    private javax.swing.JComboBox<String> cmbMonth;
    private javax.swing.JComboBox<String> cmbYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblappID;
    private javax.swing.JLabel lblpeepName;
    private javax.swing.JLabel lblpeepStatus;
    private javax.swing.JLabel lblvacLoc;
    private javax.swing.JLabel lblvacName;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
