/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Brian
 */
public class PersonnelViewParticipant_jframe extends javax.swing.JFrame {
    Personnel admin = new Personnel();
    People person = new People();
    
    public PersonnelViewParticipant_jframe() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);//make jframe center
        ArrayList<String> all_peep_data= admin.view_all_peep();
        input_table(all_peep_data);
        ArrayList<Integer> day = new ArrayList<>();//set the year and date
        for(int i = 1; i <= 31; i++) {
            day.add(i);
        }
        Integer[]dayArray=day.toArray(new Integer[0]);
        DefaultComboBoxModel days = new DefaultComboBoxModel(dayArray);
        cmbDate.setModel(days);

        ArrayList<Integer> year = new ArrayList<>();
        LocalDate current_date = LocalDate.now();
        int current_year=current_date.getYear();
        for(int i = 1900; i <= current_year; i++) {
            year.add(i);
        }
        Integer[]yearArray=year.toArray(new Integer[0]);
        DefaultComboBoxModel years = new DefaultComboBoxModel(yearArray);
        cmbYear.setModel(years);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        back_btn = new javax.swing.JButton();
        searchParticipant_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        id_radiobtn = new javax.swing.JRadioButton();
        name_radiobtn = new javax.swing.JRadioButton();
        search_txt = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        participant_table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        id_lbl = new javax.swing.JLabel();
        app_lbl = new javax.swing.JLabel();
        name_txtbox = new javax.swing.JTextField();
        add_appointment_btn = new javax.swing.JButton();
        icpass_txtbox = new javax.swing.JTextField();
        vac_radiobtn = new javax.swing.JRadioButton();
        notvac_radiobtn = new javax.swing.JRadioButton();
        citizen_radiobtn = new javax.swing.JRadioButton();
        notcitizen_radiobtn = new javax.swing.JRadioButton();
        cmbDate = new javax.swing.JComboBox<>();
        cmbMonth = new javax.swing.JComboBox<>();
        cmbYear = new javax.swing.JComboBox<>();
        modify_btn = new javax.swing.JButton();
        all_part_btn = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Participant");
        setMinimumSize(new java.awt.Dimension(810, 550));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Personnel");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("View Participant Data");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 90));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back_btn.setText("<--- Go Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel2.add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, 130, 40));

        searchParticipant_btn.setText("Search Participant");
        searchParticipant_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchParticipant_btnActionPerformed(evt);
            }
        });
        jPanel2.add(searchParticipant_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 130, 40));

        jLabel3.setText("Search by");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        id_radiobtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(id_radiobtn);
        id_radiobtn.setSelected(true);
        id_radiobtn.setText("ID");
        id_radiobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_radiobtnActionPerformed(evt);
            }
        });
        jPanel2.add(id_radiobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        name_radiobtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(name_radiobtn);
        name_radiobtn.setText("Name");
        name_radiobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_radiobtnActionPerformed(evt);
            }
        });
        jPanel2.add(name_radiobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        search_txt.setText("Enter Name/ID");
        search_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                search_txtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                search_txtFocusLost(evt);
            }
        });
        jPanel2.add(search_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 250, 40));

        participant_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fullname", "AppointmentID", "Vaccination Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        participant_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                participant_tableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(participant_table);
        if (participant_table.getColumnModel().getColumnCount() > 0) {
            participant_table.getColumnModel().getColumn(0).setResizable(false);
            participant_table.getColumnModel().getColumn(1).setResizable(false);
            participant_table.getColumnModel().getColumn(2).setResizable(false);
            participant_table.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 420, 260));

        jButton1.setText("Register New Participant");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 170, 40));

        jLabel4.setText("ID");

        jLabel5.setText("Fullname");

        jLabel6.setText("Date of birth");

        jLabel7.setText("Participant Type");

        jLabel8.setText("IC/Passport Number");

        jLabel9.setText("Vaccine Status");

        jLabel10.setText("Appointment ID");

        id_lbl.setText("-");

        app_lbl.setText("-");

        add_appointment_btn.setText("Add Appointment");
        add_appointment_btn.setEnabled(false);
        add_appointment_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_appointment_btnActionPerformed(evt);
            }
        });

        buttonGroup3.add(vac_radiobtn);
        vac_radiobtn.setText("Vaccinated");

        buttonGroup3.add(notvac_radiobtn);
        notvac_radiobtn.setSelected(true);
        notvac_radiobtn.setText("Non-Vaccinated");

        buttonGroup2.add(citizen_radiobtn);
        citizen_radiobtn.setSelected(true);
        citizen_radiobtn.setText("Citizen");

        buttonGroup2.add(notcitizen_radiobtn);
        notcitizen_radiobtn.setText("Non-Citizen");

        cmbMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        cmbMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMonthActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cmbDate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(cmbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(cmbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(notvac_radiobtn)
                    .addComponent(vac_radiobtn)
                    .addComponent(citizen_radiobtn)
                    .addComponent(notcitizen_radiobtn)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(app_lbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(add_appointment_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(icpass_txtbox, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(id_lbl, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(name_txtbox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(id_lbl)
                        .addGap(13, 13, 13)
                        .addComponent(name_txtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cmbDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(citizen_radiobtn)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notcitizen_radiobtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(icpass_txtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(app_lbl)
                            .addComponent(add_appointment_btn)
                            .addComponent(jLabel10))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(notvac_radiobtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vac_radiobtn)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 360, 360));

        modify_btn.setText("Confirm Change");
        modify_btn.setEnabled(false);
        modify_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modify_btnActionPerformed(evt);
            }
        });
        jPanel2.add(modify_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 170, 30));

        all_part_btn.setText("All Participant");
        all_part_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                all_part_btnActionPerformed(evt);
            }
        });
        jPanel2.add(all_part_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 110, 40));

        clear_btn.setText("Clear Data");
        clear_btn.setEnabled(false);
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });
        jPanel2.add(clear_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 170, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 810, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void input_table(ArrayList<String> peep_data){ //call this function whenever need to update the table
                                //use the arraylist to input table
        if (peep_data==null){
            JOptionPane.showMessageDialog(null,"Participant Not Found");
        }
        else{
            //clear jtable
            DefaultTableModel model = (DefaultTableModel)participant_table.getModel();//The table variable
            model.setRowCount(0);
            for(String data : peep_data){
                //insert a data into table
                String[] data_row = data.split(",");
                String[] selected_data={data_row[0],data_row[3],data_row[7],data_row[8]};   //must select the 3 data in each array into the table
                model.addRow(selected_data);
            }
        }
    }
    private void clear_selected(){//reset the buttons in the jframe
        modify_btn.setEnabled(false);
        clear_btn.setEnabled(true);
        id_lbl.setText("-");
        name_txtbox.setText("");
        cmbDate.setSelectedIndex(0);
        cmbYear.setSelectedIndex(0);
        cmbMonth.setSelectedIndex(0);
        citizen_radiobtn.setSelected(true);
        icpass_txtbox.setText("");
        app_lbl.setText("-");
        notvac_radiobtn.setSelected(true);
        //set all text box to empty
    }
    
    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new PersonnelHome_jframe().setVisible(true);
    }//GEN-LAST:event_back_btnActionPerformed

    private void searchParticipant_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchParticipant_btnActionPerformed
        clear_selected();
        ArrayList<String> peep_data=new ArrayList<>();
        try{
            if(id_radiobtn.isSelected()){//search by id
                String id_str = search_txt.getText();
                int id = Integer.parseInt(id_str);
                peep_data = admin.search_peep_byID(id);  //will return the whole data if found, else null;
                if(peep_data==null){
                    JOptionPane.showMessageDialog(null,"Participant Not Found");
                }else{
                    input_table(peep_data);
                }   
            }
            else{   //search by name
                String name = search_txt.getText();
                peep_data = admin.search_peep_byName(name);
                if(peep_data==null){
                    JOptionPane.showMessageDialog(null,"Participant Not Found");
                }else{
                    input_table(peep_data);
                }
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,"Incorrect Input");
        }
    }//GEN-LAST:event_searchParticipant_btnActionPerformed

    private void participant_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_participant_tableMouseClicked
        // TODO add your handling code here:
        modify_btn.setEnabled(true);
        clear_btn.setEnabled(true);//makes the button useable
        int i = participant_table.getSelectedRow();
        TableModel model=participant_table.getModel();
        int id = Integer.parseInt(model.getValueAt(i, 0).toString());//get the location from table
        ArrayList<String> selected_data = admin.search_peep_byID(id);
        person = new People(selected_data.get(0));
        id_lbl.setText(String.valueOf(person.getPeepID()));
        name_txtbox.setText(person.getPeepFullname());
        String date=person.getPeepDOB();//gets the date data
        String [] date_detail = date.split("/");
        cmbMonth.setSelectedIndex(Integer.parseInt(date_detail[1])-1);
        cmbDate.setSelectedIndex(Integer.parseInt(date_detail[0])-1);
        cmbYear.setSelectedItem(Integer.parseInt(date_detail[2])); // put the data in the combobox
        if(person.getPeepType().equals("Citizen")){//check the radio button accordingly
            citizen_radiobtn.setSelected(true);
        }else{
            notcitizen_radiobtn.setSelected(true);
        }
        icpass_txtbox.setText(person.getPeepICPass());
        app_lbl.setText(person.getPeepAppid());
        if(person.getPeepStatus().equals("Vaccinated")){//check the radio button accordingly
            vac_radiobtn.setSelected(true);
        }else{
            notvac_radiobtn.setSelected(true);
        }
        if(app_lbl.getText().equals("none")){//if there is appointment
            add_appointment_btn.setEnabled(true);
            vac_radiobtn.setEnabled(false);
        }else{//if no appointment
            add_appointment_btn.setEnabled(false);
            vac_radiobtn.setEnabled(true);
        }
    }//GEN-LAST:event_participant_tableMouseClicked

    private void search_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_search_txtFocusGained
        // TODO add your handling code here:
        search_txt.setText("");
    }//GEN-LAST:event_search_txtFocusGained

    private void id_radiobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_radiobtnActionPerformed
        // TODO add your handling code here:
        search_txt.setText("Search by ID");
    }//GEN-LAST:event_id_radiobtnActionPerformed

    private void name_radiobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_radiobtnActionPerformed
        // TODO add your handling code here:
        search_txt.setText("Search by Name");
    }//GEN-LAST:event_name_radiobtnActionPerformed

    private void all_part_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_all_part_btnActionPerformed
        // TODO add your handling code here:
        clear_selected();
        ArrayList<String> all_peep_data= admin.view_all_peep();
        input_table(all_peep_data);
    }//GEN-LAST:event_all_part_btnActionPerformed

    private void modify_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modify_btnActionPerformed
        String id=String.valueOf(person.getPeepID());
        String Username=person.getPeepUsername();
        String Password=person.getPeepPassword();
        String Fullname=name_txtbox.getText();//get information from label
        String D=String.valueOf(cmbDate.getSelectedItem());
        int Month=cmbMonth.getSelectedIndex();
        String M=String.valueOf(Month+1);
        String Y=String.valueOf(cmbYear.getSelectedItem());
        String dob= D+"/"+M+"/"+Y;//get date information from combobox and combine them
        String partiType=new String();
        if(citizen_radiobtn.isSelected()){//assign participant type from radio button
            partiType="Citizen";
        }else if(notcitizen_radiobtn.isSelected()){
            partiType="Non-Citizen";
        }
        String ICPass=icpass_txtbox.getText();
        String appid=app_lbl.getText();
        String status;
        if(vac_radiobtn.isSelected()){//assign participant status from radio button
            status="Vaccinated";
        }else{
            status="Non-Vaccinated";
        }
        String new_data=(id+","+ //combine the data into string
                        Username+","+
                        Password+","+
                        Fullname+","+
                        dob+","+
                        partiType+","+
                        ICPass+","+
                        appid+","+
                        status);
        String current_data=(new Personnel().search_peep_byID(person.getPeepID())).get(0);
        if(new_data.equals(current_data)){
            JOptionPane.showMessageDialog(null,"Inserted data the same as before, update failed");
        }
        else{
            //modify.
            User vacSys = new User();
            vacSys.modify_peep(new_data);
        }
        clear_selected();
        ArrayList<String> peep_data = admin.search_peep_byID(person.getPeepID());;
        input_table(peep_data);
    }//GEN-LAST:event_modify_btnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new PersonnelAddParticipant_jframe().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        // TODO add your handling code here:
        clear_selected();
    }//GEN-LAST:event_clear_btnActionPerformed

    private void cmbMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMonthActionPerformed
        // TODO add your handling code here:
        int Month=cmbMonth.getSelectedIndex();//set the day according to the month
        int[] one = { 0, 2, 4, 6, 7, 9, 11};
        int[] thirtee = { 3, 5, 8, 10};
        boolean foundOne = false;
        boolean foundThre=false;
        for (int n : one) {
            if (n == Month) {
                foundOne = true;
                break;
            }
        }
        for (int n : thirtee) {
            if (n == Month) {
                foundThre = true;
                break;
            }
        }
        cmbDate.removeAllItems();
        if(foundOne == true){
            String [] date = new String[31];
            for(int i = 0; i < 31; i++) {
                date[i] = String.valueOf(i + 1);
            }
            DefaultComboBoxModel days = new DefaultComboBoxModel(date);
            cmbDate.setModel(days);
        }
        else if (foundThre == true){
            String [] date = new String[30];
            for(int i = 0; i < 30; i++) {
                date[i] = String.valueOf(i + 1);
            }
            DefaultComboBoxModel days = new DefaultComboBoxModel(date);
            cmbDate.setModel(days);
        }
        else{
            String [] date = new String[28];
            for(int i = 0; i < 28; i++) {
                date[i] = String.valueOf(i + 1);
            }
            DefaultComboBoxModel days = new DefaultComboBoxModel(date);
            cmbDate.setModel(days);
        }
    }//GEN-LAST:event_cmbMonthActionPerformed

    private void add_appointment_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_appointment_btnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ParticipantAppointment_jframe(person.getPeepID(), "admin").setVisible(true);
    }//GEN-LAST:event_add_appointment_btnActionPerformed

    private void search_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_search_txtFocusLost
        // TODO add your handling code here:
        if(id_radiobtn.isSelected()){
            search_txt.setText("Search by ID");
        }
        else{
            search_txt.setText("Search by Name");
        }
    }//GEN-LAST:event_search_txtFocusLost

    
/**/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonnelViewParticipant_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonnelViewParticipant_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonnelViewParticipant_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonnelViewParticipant_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonnelViewParticipant_jframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_appointment_btn;
    private javax.swing.JButton all_part_btn;
    private javax.swing.JLabel app_lbl;
    private javax.swing.JButton back_btn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton citizen_radiobtn;
    private javax.swing.JButton clear_btn;
    private javax.swing.JComboBox<String> cmbDate;
    private javax.swing.JComboBox<String> cmbMonth;
    private javax.swing.JComboBox<String> cmbYear;
    private javax.swing.JTextField icpass_txtbox;
    private javax.swing.JLabel id_lbl;
    private javax.swing.JRadioButton id_radiobtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton modify_btn;
    private javax.swing.JRadioButton name_radiobtn;
    private javax.swing.JTextField name_txtbox;
    private javax.swing.JRadioButton notcitizen_radiobtn;
    private javax.swing.JRadioButton notvac_radiobtn;
    private javax.swing.JTable participant_table;
    private javax.swing.JButton searchParticipant_btn;
    private javax.swing.JTextField search_txt;
    private javax.swing.JRadioButton vac_radiobtn;
    // End of variables declaration//GEN-END:variables
}
