/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Brian
 */
public class PersonnelAddParticipant_jframe extends javax.swing.JFrame {

    /**
     * Creates new form PersonnelManageParticipant_jframe
     */
    public PersonnelAddParticipant_jframe() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);//make jframe center
        ArrayList<Integer> day = new ArrayList<>();//add date and year accordingly
        for(int i = 1; i <= 31; i++) {
            day.add(i);
        }
        Integer[]dayArray=day.toArray(new Integer[0]);
        DefaultComboBoxModel days = new DefaultComboBoxModel(dayArray);
        cmbDate.setModel(days);

        ArrayList<Integer> year = new ArrayList<>();
        LocalDate current_date = LocalDate.now();
        int current_year=current_date.getYear();
        for(int i = 1900; i <= current_year; i++) {
            year.add(i);
        }
        Integer[]yearArray=year.toArray(new Integer[0]);
        DefaultComboBoxModel years = new DefaultComboBoxModel(yearArray);
        cmbYear.setModel(years);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        confirm_btn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        rbtnCitizen = new javax.swing.JRadioButton();
        rbtnNonCiti = new javax.swing.JRadioButton();
        cmbDate = new javax.swing.JComboBox<>();
        cmbMonth = new javax.swing.JComboBox<>();
        cmbYear = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtFullname = new javax.swing.JTextField();
        txtNum = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txpPass = new javax.swing.JPasswordField();
        chkboxPass = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        back_btn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add New Patient");
        setMinimumSize(new java.awt.Dimension(810, 550));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Personnel");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Register New Participant");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 90));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        confirm_btn.setText("Confirm New Participant");
        confirm_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_btnActionPerformed(evt);
            }
        });
        jPanel2.add(confirm_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 180, 60));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(rbtnCitizen);
        rbtnCitizen.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        rbtnCitizen.setSelected(true);
        rbtnCitizen.setText("Citizen");
        jPanel3.add(rbtnCitizen, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        buttonGroup1.add(rbtnNonCiti);
        rbtnNonCiti.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        rbtnNonCiti.setText("Non-Citizen");
        jPanel3.add(rbtnNonCiti, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        jPanel3.add(cmbDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 50, -1));

        cmbMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        cmbMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMonthActionPerformed(evt);
            }
        });
        jPanel3.add(cmbMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        jPanel3.add(cmbYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        jLabel5.setText("Fullname");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel6.setText("Date of birth");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel7.setText("Participant Type");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel8.setText("ID/IC");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel9.setText("Password");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));
        jPanel3.add(txtFullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 240, -1));
        jPanel3.add(txtNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 220, -1));

        jLabel10.setText("User Name");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));
        jPanel3.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 240, -1));
        jPanel3.add(txpPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 140, -1));

        chkboxPass.setBackground(new java.awt.Color(102, 102, 102));
        chkboxPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chkboxPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboxPassActionPerformed(evt);
            }
        });
        jPanel3.add(chkboxPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Show Password");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 150, 40));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 430, 300));

        back_btn1.setText("<--- Go Back");
        back_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(back_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 130, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 810, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirm_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_btnActionPerformed
        // TODO add your handling code here:
        String Username=txtUsername.getText();
        String Fullname=txtFullname.getText();   
        String D=String.valueOf(cmbDate.getSelectedItem());
        int Month=cmbMonth.getSelectedIndex();
        String M=String.valueOf(Month+1);
        String Y=String.valueOf(cmbYear.getSelectedItem());
        String DOB= D+"/"+M+"/"+Y;//compile data from combobox to form a date
        String Password=String.valueOf(txpPass.getPassword());
        String ICPass=txtNum.getText();
        String partiType=new String();
        if(rbtnCitizen.isSelected()){
            partiType="Citizen";
        }
        else if(rbtnNonCiti.isSelected()){
            partiType="Non-Citizen";
        }
        People regis = new People(Username, Fullname,DOB,Password,ICPass,partiType);//gets info from table
        if("".equals(Username) || "".equals(Password) || "".equals(Fullname) || "".equals(ICPass)){//if something is left not inputted
            JOptionPane.showMessageDialog(null,"Please enter neccesary detail");
        }
        else{
            if(regis.register_peep()==true){//add participant
                this.dispose();
                new PersonnelViewParticipant_jframe().setVisible(true);
        }
        }
    }//GEN-LAST:event_confirm_btnActionPerformed

    private void back_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btn1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new PersonnelViewParticipant_jframe().setVisible(true);
    }//GEN-LAST:event_back_btn1ActionPerformed

    private void cmbMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMonthActionPerformed
        // TODO add your handling code here:
        int Month=cmbMonth.getSelectedIndex();
        int[] one = { 0, 2, 4, 6, 7, 9, 11};
        int[] thirtee = { 3, 5, 8, 10};
        boolean foundOne = false;
        boolean foundThre=false;
        for (int n : one) {
            if (n == Month) {
                foundOne = true;
                break;
            }
        }
        for (int n : thirtee) {
            if (n == Month) {
                foundThre = true;
                break;
            }
        }
        cmbDate.removeAllItems();
        if(foundOne == true){
            String [] date = new String[31];
            for(int i = 0; i < 31; i++) {
                date[i] = String.valueOf(i + 1);
            }
            DefaultComboBoxModel days = new DefaultComboBoxModel(date);
            cmbDate.setModel(days);
        }
        else if (foundThre == true){
            String [] date = new String[30];
            for(int i = 0; i < 30; i++) {
                date[i] = String.valueOf(i + 1);
            }
            DefaultComboBoxModel days = new DefaultComboBoxModel(date);
            cmbDate.setModel(days);
        }
        else{
            String [] date = new String[28];
            for(int i = 0; i < 28; i++) {
                date[i] = String.valueOf(i + 1);
            }
            DefaultComboBoxModel days = new DefaultComboBoxModel(date);
            cmbDate.setModel(days);
        }
    }//GEN-LAST:event_cmbMonthActionPerformed

    private void chkboxPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxPassActionPerformed
        // TODO add your handling code here:
        if (chkboxPass.isSelected()) {//unhide password
            txpPass.setEchoChar((char)0);
        } else {
            txpPass.setEchoChar('*');
        }
    }//GEN-LAST:event_chkboxPassActionPerformed
/**/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonnelAddParticipant_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonnelAddParticipant_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonnelAddParticipant_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonnelAddParticipant_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonnelAddParticipant_jframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkboxPass;
    private javax.swing.JComboBox<String> cmbDate;
    private javax.swing.JComboBox<String> cmbMonth;
    private javax.swing.JComboBox<String> cmbYear;
    private javax.swing.JButton confirm_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton rbtnCitizen;
    private javax.swing.JRadioButton rbtnNonCiti;
    private javax.swing.JPasswordField txpPass;
    private javax.swing.JTextField txtFullname;
    private javax.swing.JTextField txtNum;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
