/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.time.LocalDate;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);//make jframe center
        this.setBackground(new Color(0,0,0,0));
        jPanel1.setBackground(new Color(0,0,0,0));
        txtFullname.setBackground(new Color(0,0,0,0));
        txtUsername.setBackground(new Color(0,0,0,0));
        txtNum.setBackground(new Color(0,0,0,0));
        txpPass.setBackground(new Color(0,0,0,0));
        txpPasscon.setBackground(new Color(0,0,0,0));//make label and txtfield transparent

        ArrayList<Integer> day = new ArrayList<>();//input day and year combobox
        for(int i = 1; i <= 31; i++) {
            day.add(i);
        }
        Integer[]dayArray=day.toArray(new Integer[0]);
        DefaultComboBoxModel days = new DefaultComboBoxModel(dayArray);
        cmbDate.setModel(days);

        ArrayList<Integer> year = new ArrayList<>();
        LocalDate current_date = LocalDate.now();
        int current_year=current_date.getYear();
        for(int i = 1900; i <= current_year; i++) {
            year.add(i);
        }
        Integer[]yearArray=year.toArray(new Integer[0]);
        DefaultComboBoxModel years = new DefaultComboBoxModel(yearArray);
        cmbYear.setModel(years);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnClose = new javax.swing.JLabel();
        btnBack = new javax.swing.JLabel();
        btnRegis = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtNum = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        rbtnNonCiti = new javax.swing.JRadioButton();
        rbtnCitizen = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        chkboxPass = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        txpPasscon = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        txpPass = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbDate = new javax.swing.JComboBox<>();
        cmbMonth = new javax.swing.JComboBox<>();
        cmbYear = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtFullname = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsername.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(204, 204, 204));
        txtUsername.setText("Enter Username");
        txtUsername.setBorder(null);
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsernameFocusLost(evt);
            }
        });
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 350, 50));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("User Name");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 110, 60));

        jSeparator2.setBackground(java.awt.Color.gray);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 350, 30));

        btnClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Xred.png"))); // NOI18N
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });
        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 40, 50, 50));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bckBtn.png"))); // NOI18N
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 60, 40));

        btnRegis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RegisExitted.png"))); // NOI18N
        btnRegis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegisMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegisMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRegisMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnRegisMouseReleased(evt);
            }
        });
        jPanel1.add(btnRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, 110, 60));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("IC/Passport Number");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 200, 60));

        txtNum.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtNum.setForeground(new java.awt.Color(204, 204, 204));
        txtNum.setText("Enter Number");
        txtNum.setBorder(null);
        txtNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNumFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumFocusLost(evt);
            }
        });
        jPanel1.add(txtNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 340, 50));

        jSeparator5.setBackground(java.awt.Color.gray);
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 340, 30));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Are you a:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 110, 30));

        buttonGroup1.add(rbtnNonCiti);
        rbtnNonCiti.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        rbtnNonCiti.setForeground(new java.awt.Color(255, 255, 255));
        rbtnNonCiti.setText("Non-Citizen");
        jPanel1.add(rbtnNonCiti, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        buttonGroup1.add(rbtnCitizen);
        rbtnCitizen.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        rbtnCitizen.setForeground(new java.awt.Color(255, 255, 255));
        rbtnCitizen.setSelected(true);
        rbtnCitizen.setText("Citizen");
        jPanel1.add(rbtnCitizen, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Show Password");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 150, 20));

        chkboxPass.setBackground(new java.awt.Color(255, 79, 90));
        chkboxPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chkboxPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboxPassActionPerformed(evt);
            }
        });
        jPanel1.add(chkboxPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, -1, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Confirm Password");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 170, 60));

        txpPasscon.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txpPasscon.setForeground(new java.awt.Color(204, 204, 204));
        txpPasscon.setText("ConfirmPassword");
        txpPasscon.setBorder(null);
        txpPasscon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txpPassconFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txpPassconFocusLost(evt);
            }
        });
        jPanel1.add(txpPasscon, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 300, 40));

        jSeparator4.setBackground(java.awt.Color.gray);
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 300, 10));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 110, 60));

        txpPass.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txpPass.setForeground(new java.awt.Color(204, 204, 204));
        txpPass.setText("EnterPassword");
        txpPass.setBorder(null);
        txpPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txpPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txpPassFocusLost(evt);
            }
        });
        jPanel1.add(txpPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 300, 40));

        jSeparator3.setBackground(java.awt.Color.gray);
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 300, 10));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Year");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 40, 30));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Month");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 50, 30));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Date");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 40, 30));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Date of Birth");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 110, 60));

        jPanel1.add(cmbDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 50, -1));

        cmbMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        cmbMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMonthActionPerformed(evt);
            }
        });
        jPanel1.add(cmbMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        jPanel1.add(cmbYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Fullname");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 110, 60));

        txtFullname.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtFullname.setForeground(new java.awt.Color(204, 204, 204));
        txtFullname.setText("Enter Full Name");
        txtFullname.setBorder(null);
        txtFullname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFullnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFullnameFocusLost(evt);
            }
        });
        jPanel1.add(txtFullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 350, 50));

        jSeparator1.setBackground(java.awt.Color.gray);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 350, 30));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Please enter your information");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 440, 90));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RegisterBack.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 650, 530));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RegisterBack.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 630, 530));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RegisterBack2.png"))); // NOI18N
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 600, 530));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 1030, 605));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFullnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFullnameFocusGained
        // TODO add your handling code here:
        if("Enter Full Name".equals(txtFullname.getText())){
            txtFullname.setText("");
        }
    }//GEN-LAST:event_txtFullnameFocusGained

    private void txtFullnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFullnameFocusLost
        // TODO add your handling code here:
        if(txtFullname.getText().length()==0){
            txtFullname.setText("Enter Full Name");
        }
    }//GEN-LAST:event_txtFullnameFocusLost

    private void txpPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txpPassFocusGained
        // TODO add your handling code here:
        if("EnterPassword".equals(String.valueOf(txpPass.getPassword()))){
            txpPass.setText("");
        }
    }//GEN-LAST:event_txpPassFocusGained

    private void txpPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txpPassFocusLost
        // TODO add your handling code here:
        if(txpPass.getPassword().length==0){
            txpPass.setText("EnterPassword");
        }
    }//GEN-LAST:event_txpPassFocusLost

    private void txpPassconFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txpPassconFocusGained
        // TODO add your handling code here:
        if("ConfirmPassword".equals(String.valueOf(txpPasscon.getPassword()))){
            txpPasscon.setText("");
        }
    }//GEN-LAST:event_txpPassconFocusGained

    private void txpPassconFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txpPassconFocusLost
        // TODO add your handling code here:
        if(txpPasscon.getPassword().length==0){
            txpPasscon.setText("ConfirmPassword");
        }
    }//GEN-LAST:event_txpPassconFocusLost

    private void chkboxPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxPassActionPerformed
        // TODO add your handling code here:
        if (chkboxPass.isSelected()) {
            txpPass.setEchoChar((char)0);
        } else {
            txpPass.setEchoChar('*');
        }
    }//GEN-LAST:event_chkboxPassActionPerformed

    private void txtNumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumFocusGained
        // TODO add your handling code here:
        if("Enter Number".equals(txtNum.getText())){
            txtNum.setText("");
        }
    }//GEN-LAST:event_txtNumFocusGained

    private void txtNumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumFocusLost
        // TODO add your handling code here:
        if(txtNum.getText().length()==0){
            txtNum.setText("Enter Number");
        }
    }//GEN-LAST:event_txtNumFocusLost

    private void txtUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusGained
        // TODO add your handling code here:
        if("Enter Username".equals(txtUsername.getText())){
            txtUsername.setText("");
        }
    }//GEN-LAST:event_txtUsernameFocusGained

    private void txtUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusLost
        // TODO add your handling code here:
        if(txtUsername.getText().length()==0){
            txtUsername.setText("Enter Username");
        }
    }//GEN-LAST:event_txtUsernameFocusLost

    private void btnRegisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisMouseClicked
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(getClass().getResource("/Images/RegisClicked.png"));
        btnRegis.setIcon(icon);
        String Username=txtUsername.getText();
        String Fullname=txtFullname.getText();   
        String D=String.valueOf(cmbDate.getSelectedItem());
        int Month=cmbMonth.getSelectedIndex();
        String M=String.valueOf(Month+1);
        String Y=String.valueOf(cmbYear.getSelectedItem());
        String DOB= D+"/"+M+"/"+Y;//combine combobox to string date
        String Password=String.valueOf(txpPass.getPassword());
        String PassCon=String.valueOf(txpPasscon.getPassword());
        String ICPass=txtNum.getText();
        String partiType=new String();
        if(rbtnCitizen.isSelected()){//get all the inputted information
            partiType="Citizen";
        }
        else if(rbtnNonCiti.isSelected()){
            partiType="Non-Citizen";
        }
        People regis = new People(Username, Fullname,DOB,Password,ICPass,partiType);
        if("Enter Username".equals(Username) || "EnterPassword".equals(Password) || "Enter Full name".equals(Fullname) || "Enter Number".equals(ICPass)){
            JOptionPane.showMessageDialog(null,"Please enter neccesary detail"); //if any data is not inputted
        }
        else if(!(Password.equals(PassCon))){
            JOptionPane.showMessageDialog(null,"Password does not match, please re-enter");//if the password and conf password does not match
        }
        else{
            if(regis.register_peep()==true){//if the register success
                this.dispose();
                new Login().setVisible(true);
        }
        }
        
    }//GEN-LAST:event_btnRegisMouseClicked

    private void btnRegisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisMouseEntered
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(getClass().getResource("/Images/RegisEntered.png"));
        btnRegis.setIcon(icon);
    }//GEN-LAST:event_btnRegisMouseEntered

    private void btnRegisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisMouseExited
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(getClass().getResource("/Images/RegisExitted.png"));
        btnRegis.setIcon(icon);
    }//GEN-LAST:event_btnRegisMouseExited

    private void btnRegisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisMousePressed
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(getClass().getResource("/Images/RegisPressed.png"));
        btnRegis.setIcon(icon);
    }//GEN-LAST:event_btnRegisMousePressed

    private void btnRegisMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisMouseReleased
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(getClass().getResource("/Images/RegisExitted.png"));
        btnRegis.setIcon(icon);
    }//GEN-LAST:event_btnRegisMouseReleased

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_btnBackMouseClicked

    private void cmbMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMonthActionPerformed
        // TODO add your handling code here:
        int Month=cmbMonth.getSelectedIndex();//set day according to the month
        int[] one = { 0, 2, 4, 6, 7, 9, 11};
        int[] thirtee = { 3, 5, 8, 10};
        boolean foundOne = false;
        boolean foundThre=false;
        for (int n : one) {
            if (n == Month) {
              foundOne = true;
              break;
            }
          }
        for (int n : thirtee) {
            if (n == Month) {
              foundThre = true;
              break;
            }
          }
        cmbDate.removeAllItems();
        if(foundOne == true){
            String [] date = new String[31];
            for(int i = 0; i < 31; i++) {
                date[i] = String.valueOf(i + 1);
            }
            DefaultComboBoxModel days = new DefaultComboBoxModel(date);
            cmbDate.setModel(days);
        }
        else if (foundThre == true){
            String [] date = new String[30];
            for(int i = 0; i < 30; i++) {
                date[i] = String.valueOf(i + 1);
            }
            DefaultComboBoxModel days = new DefaultComboBoxModel(date);
            cmbDate.setModel(days);
        }
        else{
            String [] date = new String[28];
            for(int i = 0; i < 28; i++) {
                date[i] = String.valueOf(i + 1);
            }
            DefaultComboBoxModel days = new DefaultComboBoxModel(date);
            cmbDate.setModel(days);
        }
    }//GEN-LAST:event_cmbMonthActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel btnRegis;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkboxPass;
    private javax.swing.JComboBox<String> cmbDate;
    private javax.swing.JComboBox<String> cmbMonth;
    private javax.swing.JComboBox<String> cmbYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JRadioButton rbtnCitizen;
    private javax.swing.JRadioButton rbtnNonCiti;
    private javax.swing.JPasswordField txpPass;
    private javax.swing.JPasswordField txpPasscon;
    private javax.swing.JTextField txtFullname;
    private javax.swing.JTextField txtNum;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
